### ISSUE TITLE
Initilizing the nework with pre-trained weights

### ISSUE THREAD

**Issue by hosseinahm1367** [mseitzer/srgan#8]
Hi, I am new in deep learning and specifically transfer learning. I am trying to initialize the srrestnet with the pre-trained .pth file and use my data-set to fine-tune the weights. I tried to use the --resume option in train.py file. However, I get 'Incompatible checkpoint' error. 
Any suggestions would be helpful.

Thanks,

**Comment by mseitzer** [comment]
Finetuning should work, but not in the way you tried to do it. The `--resume` option is supposed to restart training e.g. if the training process crashed, not to initialize weights of the networks.

Instead, you need to edit the provided config file (e.g. `configs/srresnet.json`), and modify the model section as follows:

```
"model": {
  "#include": "resnet.json",
  "pretrained_weights": ["../resources/pretrained/srresnet.pth", "model"]
}
```

In the code, loading the pretrained weights happens here: https://github.com/mseitzer/srgan/blob/70f88fbac26b5a3659847965befea2fdd49eb625/training/runner.py#L60

Let me know if this works out. It's been a while since I worked on this codebase, so I might miss something.

**Comment by hosseinahm1367** [comment]
I followed your instructions. It worked perfectly. Thank you!
I do have another question though. I am trying to modify your implementation and have it trained for 8x super-resolution. Do you have any suggestions on how to proceed in the network design? Have you ever tested its performance on 8x yourself?  
I feel like I have to modify up-sampling layers. I am not sure if I have to modify anywhere else! Another solution that I was thinking of in the beginning is to do a 4x followed by a 2x SR using the pre-trained models? Do you think this trick is the same as re-designing the network for 8x? 
Thanks,

**Comment by mseitzer** [comment]
The code already supports 8x upscaling. You just need to set `"upscale_factor": 8.0` in `configs/resnet.json`. This will add another up-sampling layer (which scales by another 2x).

However, you will not be able to load the pretrained checkpoints, as they do not contain weights for the additional upsampling layer. You might be able to do so by modifying this line:
https://github.com/mseitzer/srgan/blob/70f88fbac26b5a3659847965befea2fdd49eb625/training/base_runner.py#L142
to `model.load_state_dict(state_dict, strict=False)`.

As for your suggestion, yes, you should be able to run the 4x SR followed by a 2x SR. However, this will probably not produce results of the same quality as training a proper 8x SR network, as you will have compounding errors between the two networks.

**Comment by hosseinahm1367** [comment]
This helped a lot...
Thanks!
